const plans = [
  {
    name: "Starter",
    price: "₹ 0",
    perMonth: "month",
    includes: "Includes 50 Employees",
    numberofemployees: "Limited",
    costperadditionalemployee: "Not Applicable",
    corehr: "Limited",
    payroll: "Limited",
    leavemanagement: "Limited",
    employeeworkflowsforprocessautomation: "✖️",
    attendancemanagement: "Limited",
    employeeselfonboarding: "Limited",
    comprehensiveemployeeexitmanagement: "✖️",
    employeeportalwebandmobileapp: "Limited",
    automatedchecklistsfortaskmanagement: "Limited",
  },
  {
    name: "Essential",
    price: "₹ 3495",
    perMonth: "month",
    includes: "Includes 50 Employees",
    numberofemployees: "Unlimited",
    costperadditionalemployee: "₹35/ month",
    corehr: "✅",
    payroll: "✅",
    leavemanagement: "✅",
    employeeworkflowsforprocessautomation: "Limited",
    attendancemanagement: "✖️",
    employeeselfonboarding: "✖️",
    comprehensiveemployeeexitmanagement: "✖️",
    employeeportalwebandmobileapp: "✅",
    automatedchecklistsfortaskmanagement: "✅",
  },
  {
    name: "Growth",
    price: "₹ 5495",
    perMonth: "month",
    includes: "Includes 50 Employees",
    numberofemployees: "Unlimited",
    costperadditionalemployee: "₹65/ month",
    corehr: "✅",
    payroll: "✅",
    leavemanagement: "✅",
    employeeworkflowsforprocessautomation: "✅",
    attendancemanagement: "✅",
    employeeselfonboarding: "✅",
    comprehensiveemployeeexitmanagement: "✅",
    employeeportalwebandmobileapp: "✅",
    automatedchecklistsfortaskmanagement: "✅",
  },
  {
    name: "Enterprise",
    price: "₹ 7495",
    perMonth: "month",
    includes: "Includes 50 Employees",
    numberofemployees: "Unlimited",
    costperadditionalemployee: "₹105/ month",
    corehr: "✅",
    payroll: "✅",
    leavemanagement: "✅",
    employeeworkflowsforprocessautomation: "✅",
    attendancemanagement: "✅",
    employeeselfonboarding: "✅",
    comprehensiveemployeeexitmanagement: "✅",
    employeeportalwebandmobileapp: "✅",
    automatedchecklistsfortaskmanagement: "✅",
  },
];

export default plans;
